server:
  port: 7000

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: c-server
  profiles:
    active: dev
  data:
    redis:
      host: 120.48.127.181
      port: 6379
      password: 123456 # Redis 服务器密码，如果没有则不配置
      database: 0 # Redis 数据库索引 (默认0)
      # 连接池配置 (强烈推荐生产环境使用)
      lettuce:
        pool:
          max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10   # 连接池中的最大空闲连接
          min-idle: 0    # 连接池中的最小空闲连接
          max-wait: 2000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      # 连接超时配置
      timeout: 2000ms # 连接超时时间
  jackson:
    serialization:
      fail-on-empty-beans: false # 修正：属性名使用kebab-case
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.48.127.181:5432/C_PW?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
    username: postgres
    password: 123456
  #      driver-class-name: com.mysql.jdbc.Driver
  #      url: jdbc:mysql://120.48.127.181:3306/pw?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #      username: cyd
  #      password: cyd
  # 邮箱 SMTP 配置 (移到与data同级)
  mail:
    host: smtp.qq.com
    port: 587
    username: 1205489124@qq.com
    password: keyjcuwigjlhhfac
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKeymySecretKeymySecretKey
  expiration: 86400  # 24小时

logging:
  level:
    com.pw.common.aspect: DEBUG # 为你切面包设置DEBUG级别
    root: INFO # 根日志级别

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.pw
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

mybatis-plus:
  type-handlers-package: com.pw
  #  mapper-locations: classpath:/mapper/**/*.xml
  # 搜索指定包别名
  type-aliases-package: com.pw.**.domain;com.pw.**.dto;com.pw.**.vo;
  #  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  #  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    #    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
