server:
  port: 5008

spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://120.48.127.181:3306/pw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cyd
    password: cyd
mybatis:
  mapper-locations: classpath:mapper/*.xml
